---
- name: retrieve info 
  hosts: localhost
  connection: local
  tasks:
    - name: load retrieve info role
      include_role:
        name: "../roles/retrieve_info_azure"

- name: build report with facts
  hosts:  ansible-1
  gather_facts: true
  tasks:

    - name: build a report
      include_role:
        name: "../roles/build_report_azure"
